language: python

services:
        - docker

jobs:
        include:
                - stage: test
                  script: behave
                - stage: build_image
                  script:
                          - echo $(git rev-parse --short HEAD)
                          - docker build -t python-app:$(git rev-parse --short HEAD) .

stages:
        - test
        - build_image
