language: python

git: 
        depth: false

services:
        - docker

before_install:
        - echo $(git rev-parse --short HEAD)
        - docker build -t python-app:$(git rev-parse --short HEAD) .
