language: python

services:
        - docker

install: pip install -r requirements.txt

script: behave

before_deploy:
        - echo $(git rev-parse --short HEAD)
        - docker build -t christophniederer/test-repo:$(git rev-parse --short HEAD) .
deploy:
        provider: script
        script: bash docker_push.sh christophniederer/test-repo:$(git rev-parse --short HEAD) 
