language: python

services:
        - docker

install: pip install -r requirements.txt

script: behave

before_deploy:
        - echo $(git rev-parse --short HEAD)
        - docker build -t python-app:$(git rev-parse --short HEAD) .

deploy:
        - docker images
