language: python

git: 
        depth: false

services:
        - docker


jobs:
        include:
                - stage: install
                  script: pip install -r requirements
                - stage: test
                  script: behave
                - stage: build_image
                  script:
                          - echo $(git rev-parse --short HEAD)
                          - docker build -t python-app:$(git rev-parse --short HEAD) .
