apiVersion: apps/v1
kind: Deployment
metadata:
  name: icr-deployment
  labels:
    {{- include "icr-helmchart.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "icr-helmchart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "icr-helmchart.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecret}}
      imagePullSecrets: 
      - name: {{ .Values.image.pullSecret}} 
      {{- end }}
      containers:
        - name: icr-container
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
