apiVersion: v1
kind: Service
metadata:
  name: icr-service
  labels:
    {{- include "icr-helmchart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "icr-helmchart.selectorLabels" . | nindent 4 }}
